AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AI Techne Academy - Video Processing Pipeline Infrastructure
  Phase 1.2: Base Infrastructure (S3, DynamoDB, SNS, IAM, CloudWatch)

Metadata:
  AWS::ServerlessRepo::Application:
    Name: ai-techne-academy
    Description: Automated training document generation from video transcriptions
    Author: AI Techne Academy Team
    SpdxLicenseId: MIT
    Labels: ['video-processing', 'llm', 'bedrock', 'transcription']

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name (dev, staging, or prod)

  ProjectName:
    Type: String
    Default: ai-techne-academy
    Description: Project name used for resource naming

  NotificationEmail:
    Type: String
    Default: devops@techne.com.br
    Description: Email address for SNS notifications
    AllowedPattern: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$

  InputBucketRetentionDays:
    Type: Number
    Default: 30
    Description: Days before moving input videos to Glacier

  TranscriptionBucketRetentionDays:
    Type: Number
    Default: 7
    Description: Days before deleting transcription files

  LogRetentionDays:
    Type: Number
    Default: 30
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]
    Description: CloudWatch Logs retention in days

Globals:
  Function:
    Runtime: python3.12
    Timeout: 900
    MemorySize: 1024
    Environment:
      Variables:
        LOG_LEVEL: INFO
        ENVIRONMENT: !Ref Environment
        PROJECT_NAME: !Ref ProjectName

Resources:
  # ========================================
  # S3 Buckets
  # ========================================
  
  InputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-input-${Environment}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: ArchiveOldVideos
            Status: Enabled
            Transitions:
              - TransitionInDays: !Ref InputBucketRetentionDays
                StorageClass: GLACIER
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: SAM

  OutputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-output-${Environment}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: SAM

  TranscriptionBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-transcripts-${Environment}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldTranscriptions
            Status: Enabled
            ExpirationInDays: !Ref TranscriptionBucketRetentionDays
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: SAM
        - Key: Purpose
          Value: Temporary transcription storage

  # ========================================
  # DynamoDB Table for Tracking
  # ========================================
  
  ProcessingTrackingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-tracking-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: execution_id
          AttributeType: S
        - AttributeName: video_key
          AttributeType: S
        - AttributeName: created_at
          AttributeType: S
      KeySchema:
        - AttributeName: execution_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: video-key-index
          KeySchema:
            - AttributeName: video_key
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: SAM

  # ========================================
  # SNS Topic for Notifications
  # ========================================
  
  NotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${ProjectName}-notifications-${Environment}'
      DisplayName: !Sub 'AI Techne Academy ${Environment} Notifications'
      KmsMasterKeyId: alias/aws/sns
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: SAM

  NotificationTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      TopicArn: !Ref NotificationTopic
      Endpoint: !Ref NotificationEmail

  NotificationTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref NotificationTopic
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowEventBridgeToPublish
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sns:Publish
            Resource: !Ref NotificationTopic
          - Sid: AllowLambdaToPublish
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sns:Publish
            Resource: !Ref NotificationTopic
            Condition:
              StringEquals:
                'aws:SourceAccount': !Ref 'AWS::AccountId'

  # ========================================
  # CloudWatch Log Groups
  # ========================================
  
  StateMachineLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/vendedlogs/states/${ProjectName}-${Environment}'
      RetentionInDays: !Ref LogRetentionDays
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: SAM

  ProcessorLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/ecs/${ProjectName}-processor-${Environment}'
      RetentionInDays: !Ref LogRetentionDays
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: SAM

  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-${Environment}'
      RetentionInDays: !Ref LogRetentionDays
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: SAM

  # ========================================
  # IAM Roles (Prepared for Future Use)
  # ========================================
  
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-lambda-execution-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt InputBucket.Arn
                  - !Sub '${InputBucket.Arn}/*'
                  - !GetAtt OutputBucket.Arn
                  - !Sub '${OutputBucket.Arn}/*'
                  - !GetAtt TranscriptionBucket.Arn
                  - !Sub '${TranscriptionBucket.Arn}/*'
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource:
                  - !GetAtt ProcessingTrackingTable.Arn
                  - !Sub '${ProcessingTrackingTable.Arn}/index/*'
        - PolicyName: SNSPublish
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Ref NotificationTopic
        - PolicyName: TranscribeAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - transcribe:StartTranscriptionJob
                  - transcribe:GetTranscriptionJob
                  - transcribe:ListTranscriptionJobs
                Resource: '*'
        - PolicyName: CloudWatchMetrics
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                Resource: '*'
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: SAM

  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-ecs-execution-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: SAM

  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-ecs-task-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - !Sub '${InputBucket.Arn}/*'
                  - !Sub '${TranscriptionBucket.Arn}/*'
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource:
                  - !Sub '${OutputBucket.Arn}/*'
        - PolicyName: BedrockAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                  - bedrock:InvokeModelWithResponseStream
                Resource: !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/*'
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:GetItem
                Resource: !GetAtt ProcessingTrackingTable.Arn
        - PolicyName: CloudWatchLogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub '${ProcessorLogGroup.Arn}:*'
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: SAM

# ========================================
# Outputs
# ========================================

Outputs:
  # S3 Buckets
  InputBucketName:
    Description: Name of the input S3 bucket for video uploads
    Value: !Ref InputBucket
    Export:
      Name: !Sub '${AWS::StackName}-InputBucket'

  InputBucketArn:
    Description: ARN of the input S3 bucket
    Value: !GetAtt InputBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-InputBucketArn'

  OutputBucketName:
    Description: Name of the output S3 bucket for generated documents
    Value: !Ref OutputBucket
    Export:
      Name: !Sub '${AWS::StackName}-OutputBucket'

  OutputBucketArn:
    Description: ARN of the output S3 bucket
    Value: !GetAtt OutputBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-OutputBucketArn'

  TranscriptionBucketName:
    Description: Name of the transcription S3 bucket
    Value: !Ref TranscriptionBucket
    Export:
      Name: !Sub '${AWS::StackName}-TranscriptionBucket'

  TranscriptionBucketArn:
    Description: ARN of the transcription S3 bucket
    Value: !GetAtt TranscriptionBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-TranscriptionBucketArn'

  # DynamoDB
  TrackingTableName:
    Description: Name of the DynamoDB tracking table
    Value: !Ref ProcessingTrackingTable
    Export:
      Name: !Sub '${AWS::StackName}-TrackingTable'

  TrackingTableArn:
    Description: ARN of the DynamoDB tracking table
    Value: !GetAtt ProcessingTrackingTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-TrackingTableArn'

  TrackingTableStreamArn:
    Description: Stream ARN of the DynamoDB tracking table
    Value: !GetAtt ProcessingTrackingTable.StreamArn
    Export:
      Name: !Sub '${AWS::StackName}-TrackingTableStream'

  # SNS
  NotificationTopicArn:
    Description: ARN of the SNS notification topic
    Value: !Ref NotificationTopic
    Export:
      Name: !Sub '${AWS::StackName}-NotificationTopic'

  NotificationTopicName:
    Description: Name of the SNS notification topic
    Value: !GetAtt NotificationTopic.TopicName

  # CloudWatch Log Groups
  StateMachineLogGroupName:
    Description: Name of the Step Functions log group
    Value: !Ref StateMachineLogGroup

  ProcessorLogGroupName:
    Description: Name of the ECS processor log group
    Value: !Ref ProcessorLogGroup

  LambdaLogGroupName:
    Description: Name of the Lambda functions log group
    Value: !Ref LambdaLogGroup

  # IAM Roles
  LambdaExecutionRoleArn:
    Description: ARN of the Lambda execution role
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-LambdaExecutionRole'

  ECSTaskExecutionRoleArn:
    Description: ARN of the ECS task execution role
    Value: !GetAtt ECSTaskExecutionRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ECSTaskExecutionRole'

  ECSTaskRoleArn:
    Description: ARN of the ECS task role
    Value: !GetAtt ECSTaskRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ECSTaskRole'

  # Stack Info
  StackName:
    Description: Name of this CloudFormation stack
    Value: !Ref 'AWS::StackName'

  Region:
    Description: AWS Region where resources are deployed
    Value: !Ref 'AWS::Region'

  Environment:
    Description: Environment name (dev, staging, prod)
    Value: !Ref Environment